language: java
jdk: oraclejdk7

branches:
  only:
    - master
    - release

before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # download the latest android sdk and unzip
  - wget https://dl.google.com/android/android-sdk_r24.0.1-linux.tgz
  - tar xzf android-sdk_r24.0.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo "y" | android update sdk --filter platform-tools,build-tools-21.1.2,android-21,extra-android-support,extra-android-m2repository,
  extra-google-m2repository --no-ui --obsolete --force