language: android

android:
  components:
    - android-21
    - build-tools-21.1.2
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-x86-android-21

before_script:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=256m"

script: "./gradlew clean build"

branches:
  only:
    - master
    - develop
