language: android

android:
  components:
  - platform-tools
  - tools
  - android-23
  - build-tools-23.0.2
  - extra-google-m2repository
  - extra-android-m2repository

before_script:
- GRADLE_OPTS="-Xms40m -Xmx3g -XX:MaxPermSize=3g"

script: "./gradlew check -Dpre-dex=false"

branches:
  only:
  - master
  - develop
