---
project_identifier: gdgx-frisbee 
base_url: https://api.crowdin.com

files:
  -
    source: 'app/src/main/res/values/strings.xml'
    translation: 'app/src/main/res/values-%android_code%/strings.xml'
    languages_mapping:
      android_code:
         cs: cs
         de: de
         es: es
         fr: fr
         hi: hi
         ko: ko
         lt: lt
         nl: nl
         pl: pl
         ru: ru
         sk: sk
         th: th
         tr: tr
         uk: uk

        
